name: 'Setup Docker Services'
description: 'Build, cache, and start Docker services for E2E testing'

inputs:
  github-token:
    description: 'The GITHUB_TOKEN for authenticating with ghcr.io'
    required: true
  compose-file:
    description: 'Path to the docker-compose file'
    required: false
    default: 'compose.yml'
  health-check-url:
    description: 'URL for the health check endpoint'
    required: false
    default: 'http://localhost/health'

runs:
  using: 'composite'
  steps:
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Build and start services
      shell: bash
      run: |
        docker compose -f ${{ inputs.compose-file }} up -d --build mysql redis api nginx

    - name: Wait for services to be ready
      shell: bash
      run: |
        echo "Waiting for API service to be ready..."
        # サービスの起動に時間がかかる場合があるため、最初の待機時間を設ける
        sleep 15

        max_attempts=30
        attempt=1

        while [ $attempt -le $max_attempts ]; do
          # -s: サイレント, -f: エラー時に失敗, -o /dev/null: 出力破棄
          if curl -s -f -o /dev/null ${{ inputs.health-check-url }}; then
            echo "✅ API is ready!"
            exit 0
          fi

          if [ $attempt -eq $max_attempts ]; then
            echo "❌ API failed to start within timeout."
            # 失敗時はデバッグ用にログを出力
            docker compose -f ${{ inputs.compose-file }} logs api
            exit 1
          fi

          echo "Attempt $attempt/$max_attempts - API not ready yet, waiting 2 seconds..."
          sleep 2
          attempt=$((attempt + 1))
        done
